spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/empaquesdesa
spring.datasource.username=root
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/empaques-desa/api

logging.level.org.springframework.security.web.*=debug

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=estebanv0614@gmail.com
spring.mail.password=puxjaeovzibmwuqr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.notificacion.email-admin=estebanv0614@gmail.com